/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "main.h"


bool extiflg = 0;

int main(void)
{
  rcc_HSE_Configuration();
  rcc_Systick_Configuration(72000);
  uart_UART1_GPIO_Configuration();
  uart_UART1_Configuration();
  exti_PB_config();
  printf("Programming is starting...\n");

  while(1)
  {
    if(extiflg)
    {
      extiflg = false;
       gpio_LEDs_TogglePB13();
        printf("Button interrupt\n");
        rcc_MsTicks_Delay(200);
         EXTI->IMR |= EXTI_IMR_IM0;
    }
  }
}


void EXTI0_IRQHandler()
{
  //clear pending register
  NVIC_ClearPendingIRQ(EXTI0_IRQn);
  //set pending register
  EXTI->PR = EXTI_PR_PR0;


  //application for interrupt
  //Remask
  EXTI->IMR &= ~(EXTI_IMR_IM0);
  extiflg = 1;

}
