/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "main.h"


int main(void)
{
  //Set 72MHz clock
  rcc_HSE_Configuration();
  //Re-load value ARR =AHB/1000 = 72MHz/1000 = 72000
  rcc_Systick_Configuration(72000);

  while(1)
  {

  }
}
